# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sex', models.CharField(max_length=120)),
                ('date_of_birth', models.CharField(max_length=120)),
                ('email_ID', models.EmailField(max_length=200)),
                ('mobile_no', models.CharField(max_length=120)),
                ('father_name', models.CharField(max_length=120)),
                ('mother_name', models.CharField(max_length=120)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=120)),
                ('Qualification', models.TextField()),
                ('achievement', models.TextField()),
                ('job_experience', models.TextField()),
                ('hobbies', models.TextField()),
                ('marital_status', models.CharField(max_length=120)),
                ('references', models.TextField()),
            ],
        ),
    ]
